version: '2'
services:
  web:
    build:
      context: .
      args:
        - LOCAL_BUILD=true
    volumes:
      - mtsmfm-rails-system-test-example-sync:/app
volumes:
  mtsmfm-rails-system-test-example-sync:
    external: true
