# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

shared:
  api_key: 123

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 99ec4f7438e5b29f79bb79cff28c19fcadc08ae59416b50599b2475bd4f9f49d4e9a29745122051bad405ebccaa3fec9782c4aab758cbd391f4702cfbd838832

test:
  secret_key_base: d05d2cdf04a5654fb04fbb84e7a34cb9238b6416d40588781d353aade4b10d835f5f6b4510a00455c1fc87cc0c1ab4f1120c233d6c70961fd8274ab880ccf69d

# Do not keep production secrets in the repository,
# instead read values from the environment.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
